### ISSUE TITLE
Paper information error

### ISSUE THREAD

**Issue by MetaT1an** [chaoyanghe/Awesome-Federated-Learning#2]
Please check if the information of the paper is correct:

> [Can You Really Backdoor Federated Learning?](https://arxiv.org/pdf/1911.07963.pdf)(**NerulPS 2019??**)

I don't see any evidence that the paper was accepted by NerulPS 2019.

**Comment by weimingwill** [comment]
It is in NIPS2019 workshop

**Comment by chaoyanghe** [comment]
right, it's in NeurIPS 2019 FL workshop

**Comment by MetaT1an** [comment]
Thanks. >_<
